// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NkochnevCore.Infrastructure.Data;
using System;

namespace NkochnevCore.Infrastructure.Migrations
{
    [DbContext(typeof(NkochnevDataContext))]
    [Migration("20180309140610_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NkochnevCore.Infrastructure.Domain.ArticleDomain", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100);

                    b.Property<string>("Content");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Preview");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(1000);

                    b.Property<string>("SeoKeyWords")
                        .HasMaxLength(1000);

                    b.Property<string>("Title")
                        .HasMaxLength(1000);

                    b.HasKey("Key");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("NkochnevCore.Infrastructure.Domain.AuthDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PassHash")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Auth");
                });

            modelBuilder.Entity("NkochnevCore.Infrastructure.Domain.AuthTokenDomain", b =>
                {
                    b.Property<string>("RefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<DateTime>("Expiresin");

                    b.Property<string>("JwtToken");

                    b.HasKey("RefreshToken");

                    b.ToTable("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
