// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NkochnevCore.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NkochnevCore.Infrastructure.Migrations
{
    [DbContext(typeof(NkochnevDataContext))]
    [Migration("20190928101842_addedIsDraftField")]
    partial class addedIsDraftField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NkochnevCore.Infrastructure.Domain.ArticleDomain", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100);

                    b.Property<string>("Content");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsDraft");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Preview");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(1000);

                    b.Property<string>("SeoKeyWords")
                        .HasMaxLength(1000);

                    b.Property<string>("Title")
                        .HasMaxLength(1000);

                    b.HasKey("Key");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("NkochnevCore.Infrastructure.Domain.AuthDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PassHash")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Auth");
                });

            modelBuilder.Entity("NkochnevCore.Infrastructure.Domain.AuthTokenDomain", b =>
                {
                    b.Property<string>("RefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<DateTime>("Expiresin");

                    b.Property<string>("JwtToken")
                        .IsRequired();

                    b.Property<bool>("RefreshTokenValid")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.HasKey("RefreshToken");

                    b.ToTable("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
